### ISSUE TITLE
Standardize multisite config split machine names

### ISSUE THREAD

**Issue by richardbporter** [uiowa/uiowa#2359]
### Problem
We cannot execute Drush/BLT commands targeting all multisite config splits because the machine names are all different. We (I) documented that multisite splits should be named the same as the URI. In hindsight, having them all be the same would be useful.

Ideally, we would be able to do something like this:
`blt uiowa:multisite:execute 'config-split:export site'`

### Proposed Solution
- [x] #4095
- [x] #4096
- [x] Update multisite split machine names to be "site". 
  - [x] Move site splits to subdirectory under config/sites/
  - [x] Update docs.

**Comment by joewhitsitt** [comment]
"site" like `admissions` or "site" like `admissions_uiowa_edu`?

**Comment by pyrello** [comment]
I think like `site_admissions_uiowa_edu`

**Comment by richardbporter** [comment]
I was thinking literally `site` so that we can run the command above, i.e. export each site split en masse. Since site splits exist in site splits, there shouldn't be any conflicts.

**Comment by mark-bennett-uiowa** [comment]
Ive been creating my site splits with labels like admissions.uiowa.edu. The machine name becomes admissions_uiowa_edu then. Shouldn't we avoid any naming conflicts either way (whether we prepend 'site_' to the front or not)??

**Comment by richardbporter** [comment]
The directory would still be different per site obviously because they have to be. Just talking the machine name here.

**Comment by richardbporter** [comment]
Here is en example scenario of why I thought this would be useful.

I need to update the same configuration in multiple site splits. ~~I write an update hook that modifies the configuration.~~ I run `blt uiowa:multisite:execute 'config:set foo bar'` on the sites and then run `blt uiowa:multisite:execute 'config-split:export site` to export each site's `site` config split. We can't do this right now.

**Comment by richardbporter** [comment]
Sorry, update hook was a bad example. I meant just a Drush command to set some arbitrary config or add a permission, etc.

**Comment by mark-bennett-uiowa** [comment]
Agreed. So directory would be `../config/sitename.example.edu`, label would be `sitename.example.edu`, and machine name is `sitename_example_edu`, correct?

**Comment by richardbporter** [comment]
After all the subtasks, each site split would be named `site`  with folder location `../config/sites/sitename.example.edu`. The machine name is controlled by the config entity name so we'd be renaming all site splits to `config_split.config_split.site`. It'll require an update hook to import that.

**Comment by richardbporter** [comment]
Step 1 of this issue could involve removing any site split config directories that are empty. I don't remember exactly what the error was that caused me to create empty config dirs. This references an error related to AC task log during deployments: https://github.com/uiowa/uiowa/commit/09d6a61f8d9bf539719df570bff4ad7f61ca8aa3#diff-a2a23b52786f9fb65b086307669cfd9c9868752bf2b9e925adc98784c153931d I think its because Acquia assumes we're using the `vcs` config storage which we are now unsetting in global.settings.php file.

I don't think these empty directories are adding any value. I'd be in favor of removing them, if possible, which would help identify "custom" sites more easily.

**Comment by pyrello** [comment]
> I don't think these empty directories are adding any value. I'd be in favor of removing them, if possible, which would help identify "custom" sites more easily.

Big +1 to that. Scrolling through all those config directories is a pain too when you need to do comparisons between similar files.

**Comment by richardbporter** [comment]
> Step 1 of this issue could involve removing any site split config directories that are empty. I don't remember exactly what the error was that caused me to create empty config dirs. This references an error related to AC task log during deployments: [09d6a61#diff-a2a23b52786f9fb65b086307669cfd9c9868752bf2b9e925adc98784c153931d](https://github.com/uiowa/uiowa/commit/09d6a61f8d9bf539719df570bff4ad7f61ca8aa3#diff-a2a23b52786f9fb65b086307669cfd9c9868752bf2b9e925adc98784c153931d) I think its because Acquia assumes we're using the `vcs` config storage which we are now unsetting in global.settings.php file.
> 
> I don't think these empty directories are adding any value. I'd be in favor of removing them, if possible, which would help identify "custom" sites more easily.

I think we could get around that error, if it still exists, by creating these empty directories in the Travis artifact build process thereby keeping them out of our source repo.

**Comment by richardbporter** [comment]
Here is an example of a split named `site`: https://github.com/uiowa/uiowa/pull/4013/files#diff-2107cb765cb7d6f77d3aa84431a663e7ada1e664ec7bc5347d7827566beb7746 The description and folder still have the actual site name/URI in them but exporting uses the id: `site`.

**Comment by pyrello** [comment]
I don't understand why we can't just get a list of all the site split names by scanning the folders and looking for a `config_split.config_split.*` file.

It may not actually end up being a problem, but it seems like this might be a little confusing when actually running imports and exports.

**Comment by richardbporter** [comment]
I merged the removal of empty config directories into develop, deployed it and I'm not seeing the error mentioned in https://github.com/uiowa/uiowa/issues/2359#issuecomment-862657765. I think this is because we unset the vcs config directory after I reported it so AC is not checking for its existence.

Jun 2019: https://github.com/uiowa/uiowa/commit/09d6a61f8d9bf539719df570bff4ad7f61ca8aa3#diff-a2a23b52786f9fb65b086307669cfd9c9868752bf2b9e925adc98784c153931d

Aug 2019: https://github.com/uiowa/uiowa/commit/b6f360abe2c40825262d9ccda00695e8afdb7201

**Comment by richardbporter** [comment]
Just noticed that the following sites have config splits with nothing in them (besides the split itself):

- africanamericanstudies.uiowa.edu
- americanstudies.uiowa.edu
- anthropology.uiowa.edu
- globalhealthstudies.uiowa.edu
- interdepartmentalstudies.uiowa.edu
- interdisciplinaryprograms.uiowa.edu
- internationalstudies.uiowa.edu
- latinamericanstudies.uiowa.edu
- latinxstudies.uiowa.edu
- nativeamericanstudies.uiowa.edu
- socialwork.uiowa.edu

@mark-bennett-uiowa are these still needed?

**Comment by mark-bennett-uiowa** [comment]
@richardbporter No, not at this time. I ended up creating them during the creation in case I did need them. At this point, they still dont have anything in them.
